# RSI交易系统配置文件
# 币安合约 SOLUSDT 实时数据获取、RSI 计算和自动交易

# 交易对配置
trading:
  symbol: 'SOLUSDT'                    # 交易对
  interval: '15m'                      # K线时间周期 (1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M)
  testnet: false                       # 是否使用测试网络

# RSI指标配置
rsi:
  period: 6                            # RSI计算周期
  oversold: 40                        # RSI超卖阈值
  overbought: 78                       # RSI超买阈值

# 仓位管理配置
position:
  ratio: 0.9                           # 每次下单占余额的比例 (0.0-1.0)
  leverage: 15                         # 合约杠杆倍数
  max_ratio: 1.0                       # 最大持仓比例，防止过度杠杆

# 止盈止损配置
risk_management:
  stop_loss_pct: 0.001                # 止损百分比 (0.5%)
  take_profit_pct: 0.001             # 止盈百分比 (0.5%)
  emergency_stop_loss: 0.10           # 紧急止损 (10%)
  max_position_time: 604800           # 最大持仓时间 (秒) - 7天

# 移动止损配置
trailing_stop:
  enabled: false                       # 是否启用移动止损
  distance: 0.02                       # 移动止损距离 (2%)

# 交易频率控制
trading_limits:
  order_cooldown: 600                 # 下单冷却时间 (秒) - 10分钟
  max_daily_trades: 10                # 每日最大交易次数
  max_daily_loss: 50                  # 每日最大亏损 (USDT)

# 日志配置
logging:
  level: 'INFO'                        # 日志级别 (DEBUG, INFO, WARNING, ERROR)
  file_format: 'logs/rsi_trading_%Y%m%d.log'  # 日志文件格式
  console_output: true                 # 是否输出到控制台

# 数据配置
data:
  historical_limit: 100               # 获取历史K线数据的数量
  max_data_points: 200               # 内存中保留的最大数据点数量
  realtime_update_interval: 1        # 实时数据更新间隔 (秒)

# 网络配置
network:
  proxy: 'http://127.0.0.1:8800'  # 代理服务器 (可选)
  websocket_timeout: 30              # WebSocket连接超时时间 (秒)
  reconnect_attempts: 3              # 重连尝试次数

# 通知配置 (预留)
notifications:
  enabled: false                      # 是否启用通知
  telegram_bot_token: ''             # Telegram机器人token
  telegram_chat_id: ''               # Telegram聊天ID
  email_enabled: false               # 是否启用邮件通知
  email_smtp_server: ''              # SMTP服务器
  email_username: ''                 # 邮箱用户名
  email_password: ''                 # 邮箱密码
  email_recipients: []               # 收件人列表

# 高级配置
advanced:
  enable_short_trading: true         # 是否启用做空交易
  enable_long_trading: true          # 是否启用做多交易
  min_order_quantity: 0.01           # 最小下单数量
  price_precision: 4                 # 价格精度
  quantity_precision: 2              # 数量精度
  enable_test_mode: false            # 是否启用测试模式
